trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  dockerRegistryConnection: 'mydocker'
  imageRepository: 'meghanshu0/tikkle-app'
  tag: 'latest'

steps:
- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    command: buildAndPush
    containerRegistry: $(dockerRegistryConnection)
    repository: $(imageRepository)
    dockerfile: '$(Build.SourcesDirectory)/tikkle/Dockerfile'
    tags: |
      $(tag)