trigger:
- main

resources:
- repo: self

variables:
  tag: 'latest'
  dockerRegistryConnection: 'DockerHubConnection'
  imageRepository: 'meghanshu0/tikkle-app'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryConnection)
        dockerfile: '$(Build.SourcesDirectory)/tikkle/Dockerfile'
        tags: |
          $(tag)